puppet_server_packages:
  - puppetserver
  - puppetdb-termini
  - puppetdb
  - facter
puppet_agent_package: puppet-agent
puppet_repository_url: "https://apt.puppetlabs.com/puppet7-release-{{ ansible_distribution_release }}.deb"
puppet_repository_key_url: "https://apt.puppetlabs.com/DEB-GPG-KEY-puppet-20250406"
universe_repositories:
  - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
  - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release  }}-updates universe"
  - "deb http://security.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe"
puppet_bin_path: /opt/puppetlabs/bin/
puppet_server_services:
  - puppetserver
  - puppetdb
puppetdb_config_path: /etc/puppetlabs/puppetdb/conf.d
puppet_agent_service: puppet
puppet_config_path: /etc/puppetlabs/puppet